
services:
  postgresql:
    image: postgres:13
    container_name: pgsql
    ports:
      - "5433:5432"  # Избегаем конфликта с локальной БД
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app_api:
    build:
      context:  ./fastapi_server
    container_name: backend_container
    depends_on:
      - postgresql
    environment:
      FAST_API_HOST: 0.0.0.0
      FAST_API_PORT: 8000
      DBNAME: ${DBNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgresql
      DB_PORT: 5432
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      FREEKASSA_MERCHANT_ID: ${FREEKASSA_MERCHANT_ID}
      FREEKASSA_SECRET_WORD: ${FREEKASSA_SECRET_WORD}
      FREEKASSA_SECRET_WORD2: ${FREEKASSA_SECRET_WORD2}
    ports:
      - "8000:8000"
    restart: unless-stopped

  telegram_bot:
    build:
      context: ./bot
    container_name: telegram_bot
    depends_on:
      - postgresql
      - app_api
    environment:
      DBNAME: ${DBNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgresql
      DB_PORT: 5432
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped

volumes:
  postgres_data: